ESX.RegisterSetting("HealthRegeneration", "Health Regeneration", "Adjustments", false)
ESX.RegisterSetting("VehicleRewards", "Vehicle Rewards", "Adjustments", false)
ESX.RegisterSetting("NPCDrops", "NPC Drops", "Adjustments", false)
ESX.RegisterSetting("DispatchServices", "Dispatch Services", "Adjustments", true)
ESX.RegisterSetting("Scenarios", "Scenarios", "Adjustments", true)
ESX.RegisterSetting("AimAssist", "Aim Assist", "Adjustments", false)
ESX.RegisterSetting("VehicleSeatShuff", "Seat Shuffle", "Adjustments", false)
ESX.RegisterSetting("DisplayAmmo", "Display Ammo", "Adjustments", false)
ESX.RegisterSetting("PVP", "PVP", "Adjustments", true)
ESX.RegisterSetting("WantedLevel", "Wanted Level", "Adjustments", false)
ESX.RegisterSetting("AIPlates", "AI Plate Text", "Adjustments",  "........")

ESX.RegisterSetting("HUD:1", "Wanted Stars", "HUD Components",  false)
ESX.RegisterSetting("HUD:2", "Weapon Icon", "HUD Components",  false)
ESX.RegisterSetting("HUD:3", "Cash", "HUD Components",  false)
ESX.RegisterSetting("HUD:4", "MP Cash", "HUD Components",  false)
ESX.RegisterSetting("HUD:5", "MP Message", "HUD Components",  false)
ESX.RegisterSetting("HUD:6", "Vehicle Name", "HUD Components",  true)
ESX.RegisterSetting("HUD:7", "Area Name", "HUD Components",  true)
ESX.RegisterSetting("HUD:8", "Vehicle Class", "HUD Components",  true)
ESX.RegisterSetting("HUD:9", "Street Name", "HUD Components",  true)
ESX.RegisterSetting("HUD:10", "Help Text", "HUD Components",  false)
ESX.RegisterSetting("HUD:11", "Floating Help Text 1", "HUD Components",  false)
ESX.RegisterSetting("HUD:12", "Floating Help Text 2", "HUD Components",  false)
ESX.RegisterSetting("HUD:13", "Cash Change", "HUD Components",  false)
ESX.RegisterSetting("HUD:14", "Reticle", "HUD Components",  false)
ESX.RegisterSetting("HUD:15", "Subtitle Text", "HUD Components",  false)
ESX.RegisterSetting("HUD:16", "Radio Stations", "HUD Components",  false)
ESX.RegisterSetting("HUD:17", "Saving Game", "HUD Components",  false)
ESX.RegisterSetting("HUD:18", "Game Stream", "HUD Components",  false)
ESX.RegisterSetting("HUD:19", "Weapon Wheel", "HUD Components",  false)
ESX.RegisterSetting("HUD:20", "Weapon Wheel Stats", "HUD Components",  false)
ESX.RegisterSetting("HUD:21", "HUD Components", "HUD Components",  false)
ESX.RegisterSetting("HUD:22", "HUD Weapons", "HUD Components",  false)

ESX.RegisterSetting("discord:appId", "App Id", "Discord Activity",  "0")
ESX.RegisterSetting("discord:assetName", "Asset Name", "Discord Activity",  "LargeIcon")
ESX.RegisterSetting("discord:assetText", "Asset Text", "Discord Activity",  "{server_name}")
ESX.RegisterSetting("discord:buttonsLabel:1", "Button 1 Label", "Discord Activity",  "Join Server")
ESX.RegisterSetting("discord:buttonsUrl:1", "Button 1 Url", "Discord Activity",  "fivem://connect/{server_endpoint}")
ESX.RegisterSetting("discord:buttonsLabel:2", "Button 2 Label", "Discord Activity",  "Discord")
ESX.RegisterSetting("discord:buttonsUrl:2", "Button 2 Url", "Discord Activity",  "https://discord.esx-framework.org")
ESX.RegisterSetting("discord:presence", "Presence", "Discord Activity",  "{player_name} [{player_id}] | {server_players}/{server_maxplayers}")
ESX.RegisterSetting("discord:refresh", "Refresh", "Discord Activity",  60000)

ESX.RegisterSetting("Paycheck", "Player Paycheck", "General",  true)
ESX.RegisterSetting("LogPaycheck", "Paycheck Logging", "General",  false)
ESX.RegisterSetting("SocietyPayouts", "Society Payouts", "General",  false)
ESX.RegisterSetting("PaycheckInterval", "Paycheck Interval", "General",  7)
ESX.RegisterSetting("PayCheckMultiplier", "Off-Duty Paycheck Multiplier", "General",  0.5)
ESX.RegisterSetting("MaxWeight", "Max Weight", "General",  24)
ESX.RegisterSetting("DefaultDuty", "Default Duty", "General",  false)
ESX.RegisterSetting("SaveDeath", "Save Death Status", "General",  true)
ESX.RegisterSetting("LogAdmins", "Log Admins", "General",  false)
ESX.RegisterSetting("UIColour", "UI Colour", "General",  "#FB9B04")



