const Nationalities: { value: string; label: string; flag: string }[] = [
	{ value: 'Afghanistan', label: 'Afghanistan', flag: '🇦🇫' },
	{ value: 'Albania', label: 'Albania', flag: '🇦🇱' },
	{ value: 'Algeria', label: 'Algeria', flag: '🇩🇿' },
	{ value: 'Andorra', label: 'Andorra', flag: '🇦🇩' },
	{ value: 'Angola', label: 'Angola', flag: '🇦🇴' },
	{ value: 'Antigua and Barbuda', label: 'Antigua and Barbuda', flag: '🇦🇬' },
	{ value: 'Argentina', label: 'Argentina', flag: '🇦🇷' },
	{ value: 'Armenia', label: 'Armenia', flag: '🇦🇲' },
	{ value: 'Australia', label: 'Australia', flag: '🇦🇺' },
	{ value: 'Austria', label: 'Austria', flag: '🇦🇹' },
	{ value: 'Azerbaijan', label: 'Azerbaijan', flag: '🇦🇿' },
	{ value: 'Bahamas', label: 'Bahamas', flag: '🇧🇸' },
	{ value: 'Bahrain', label: 'Bahrain', flag: '🇧🇭' },
	{ value: 'Bangladesh', label: 'Bangladesh', flag: '🇧🇩' },
	{ value: 'Barbados', label: 'Barbados', flag: '🇧🇧' },
	{ value: 'Belarus', label: 'Belarus', flag: '🇧🇾' },
	{ value: 'Belgium', label: 'Belgium', flag: '🇧🇪' },
	{ value: 'Belize', label: 'Belize', flag: '🇧🇿' },
	{ value: 'Benin', label: 'Benin', flag: '🇧🇯' },
	{ value: 'Bhutan', label: 'Bhutan', flag: '🇧🇹' },
	{ value: 'Bolivia', label: 'Bolivia', flag: '🇧🇴' },
	{ value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina', flag: '🇧🇦' },
	{ value: 'Botswana', label: 'Botswana', flag: '🇧🇼' },
	{ value: 'Brazil', label: 'Brazil', flag: '🇧🇷' },
	{ value: 'Brunei Darussalam', label: 'Brunei Darussalam', flag: '🇧🇳' },
	{ value: 'Bulgaria', label: 'Bulgaria', flag: '🇧🇬' },
	{ value: 'Burkina Faso', label: 'Burkina Faso', flag: '🇧🇫' },
	{ value: 'Burundi', label: 'Burundi', flag: '🇧🇮' },
	{ value: 'Cabo Verde', label: 'Cabo Verde', flag: '🇨🇻' },
	{ value: 'Cambodia', label: 'Cambodia', flag: '🇰🇭' },
	{ value: 'Cameroon', label: 'Cameroon', flag: '🇨🇲' },
	{ value: 'Canada', label: 'Canada', flag: '🇨🇦' },
	{ value: 'Central African Republic', label: 'Central African Republic', flag: '🇨🇫' },
	{ value: 'Chad', label: 'Chad', flag: '🇹🇩' },
	{ value: 'Chile', label: 'Chile', flag: '🇨🇱' },
	{ value: 'China', label: 'China', flag: '🇨🇳' },
	{ value: 'Colombia', label: 'Colombia', flag: '🇨🇴' },
	{ value: 'Comoros', label: 'Comoros', flag: '🇰🇲' },
	{ value: 'Congo (Congo-Brazzaville)', label: 'Congo (Congo-Brazzaville)', flag: '🇨🇬' },
	{ value: 'Congo (Democratic Republic of the)', label: 'Congo (Democratic Republic of the)', flag: '🇨🇩' },
	{ value: 'Costa Rica', label: 'Costa Rica', flag: '🇨🇷' },
	{ value: 'Croatia', label: 'Croatia', flag: '🇭🇷' },
	{ value: 'Cuba', label: 'Cuba', flag: '🇨🇺' },
	{ value: 'Cyprus', label: 'Cyprus', flag: '🇨🇾' },
	{ value: 'Czech Republic', label: 'Czech Republic', flag: '🇨🇿' },
	{ value: 'Denmark', label: 'Denmark', flag: '🇩🇰' },
	{ value: 'Djibouti', label: 'Djibouti', flag: '🇩🇯' },
	{ value: 'Dominica', label: 'Dominica', flag: '🇩🇲' },
	{ value: 'Dominican Republic', label: 'Dominican Republic', flag: '🇩🇴' },
	{ value: 'Ecuador', label: 'Ecuador', flag: '🇪🇨' },
	{ value: 'Egypt', label: 'Egypt', flag: '🇪🇬' },
	{ value: 'El Salvador', label: 'El Salvador', flag: '🇸🇻' },
	{ value: 'Equatorial Guinea', label: 'Equatorial Guinea', flag: '🇬🇶' },
	{ value: 'Eritrea', label: 'Eritrea', flag: '🇪🇷' },
	{ value: 'Estonia', label: 'Estonia', flag: '🇪🇪' },
	{ value: 'Eswatini', label: 'Eswatini', flag: '🇸🇿' },
	{ value: 'Ethiopia', label: 'Ethiopia', flag: '🇪🇹' },
	{ value: 'Fiji', label: 'Fiji', flag: '🇫🇯' },
	{ value: 'Finland', label: 'Finland', flag: '🇫🇮' },
	{ value: 'France', label: 'France', flag: '🇫🇷' },
	{ value: 'Gabon', label: 'Gabon', flag: '🇬🇦' },
	{ value: 'Gambia', label: 'Gambia', flag: '🇬🇲' },
	{ value: 'Georgia', label: 'Georgia', flag: '🇬🇪' },
	{ value: 'Germany', label: 'Germany', flag: '🇩🇪' },
	{ value: 'Ghana', label: 'Ghana', flag: '🇬🇭' },
	{ value: 'Greece', label: 'Greece', flag: '🇬🇷' },
	{ value: 'Grenada', label: 'Grenada', flag: '🇬🇩' },
	{ value: 'Guatemala', label: 'Guatemala', flag: '🇬🇹' },
	{ value: 'Guinea', label: 'Guinea', flag: '🇬🇳' },
	{ value: 'Guinea-Bissau', label: 'Guinea-Bissau', flag: '🇬🇼' },
	{ value: 'Guyana', label: 'Guyana', flag: '🇬🇾' },
	{ value: 'Haiti', label: 'Haiti', flag: '🇭🇹' },
	{ value: 'Honduras', label: 'Honduras', flag: '🇭🇳' },
	{ value: 'Hungary', label: 'Hungary', flag: '🇭🇺' },
	{ value: 'Iceland', label: 'Iceland', flag: '🇮🇸' },
	{ value: 'India', label: 'India', flag: '🇮🇳' },
	{ value: 'Indonesia', label: 'Indonesia', flag: '🇮🇩' },
	{ value: 'Iran', label: 'Iran', flag: '🇮🇷' },
	{ value: 'Iraq', label: 'Iraq', flag: '🇮🇶' },
	{ value: 'Ireland', label: 'Ireland', flag: '🇮🇪' },
	{ value: 'Israel', label: 'Israel', flag: '🇮🇱' },
	{ value: 'Italy', label: 'Italy', flag: '🇮🇹' },
	{ value: 'Jamaica', label: 'Jamaica', flag: '🇯🇲' },
	{ value: 'Japan', label: 'Japan', flag: '🇯🇵' },
	{ value: 'Jordan', label: 'Jordan', flag: '🇯🇴' },
	{ value: 'Kazakhstan', label: 'Kazakhstan', flag: '🇰🇿' },
	{ value: 'Kenya', label: 'Kenya', flag: '🇰🇪' },
	{ value: 'Kiribati', label: 'Kiribati', flag: '🇰🇮' },
	{ value: 'Korea (North)', label: 'Korea (North)', flag: '🇰🇵' },
	{ value: 'Korea (South)', label: 'Korea (South)', flag: '🇰🇷' },
	{ value: 'Kuwait', label: 'Kuwait', flag: '🇰🇼' },
	{ value: 'Kyrgyzstan', label: 'Kyrgyzstan', flag: '🇰🇬' },
	{ value: 'Laos', label: 'Laos', flag: '🇱🇦' },
	{ value: 'Latvia', label: 'Latvia', flag: '🇱🇻' },
	{ value: 'Lebanon', label: 'Lebanon', flag: '🇱🇧' },
	{ value: 'Lesotho', label: 'Lesotho', flag: '🇱🇸' },
	{ value: 'Liberia', label: 'Liberia', flag: '🇱🇷' },
	{ value: 'Libya', label: 'Libya', flag: '🇱🇾' },
	{ value: 'Liechtenstein', label: 'Liechtenstein', flag: '🇱🇮' },
	{ value: 'Lithuania', label: 'Lithuania', flag: '🇱🇹' },
	{ value: 'Luxembourg', label: 'Luxembourg', flag: '🇱🇺' },
	{ value: 'Madagascar', label: 'Madagascar', flag: '🇲🇬' },
	{ value: 'Malawi', label: 'Malawi', flag: '🇲🇼' },
	{ value: 'Malaysia', label: 'Malaysia', flag: '🇲🇾' },
	{ value: 'Maldives', label: 'Maldives', flag: '🇲🇻' },
	{ value: 'Mali', label: 'Mali', flag: '🇲🇱' },
	{ value: 'Malta', label: 'Malta', flag: '🇲🇹' },
	{ value: 'Marshall Islands', label: 'Marshall Islands', flag: '🇲🇭' },
	{ value: 'Mauritania', label: 'Mauritania', flag: '🇲🇷' },
	{ value: 'Mauritius', label: 'Mauritius', flag: '🇲🇺' },
	{ value: 'Mexico', label: 'Mexico', flag: '🇲🇽' },
	{ value: 'Micronesia', label: 'Micronesia', flag: '🇫🇲' },
	{ value: 'Moldova', label: 'Moldova', flag: '🇲🇩' },
	{ value: 'Monaco', label: 'Monaco', flag: '🇲🇨' },
	{ value: 'Mongolia', label: 'Mongolia', flag: '🇲🇳' },
	{ value: 'Montenegro', label: 'Montenegro', flag: '🇲🇪' },
	{ value: 'Morocco', label: 'Morocco', flag: '🇲🇦' },
	{ value: 'Mozambique', label: 'Mozambique', flag: '🇲🇿' },
	{ value: 'Myanmar', label: 'Myanmar', flag: '🇲🇲' },
	{ value: 'Namibia', label: 'Namibia', flag: '🇳🇦' },
	{ value: 'Nauru', label: 'Nauru', flag: '🇳🇷' },
	{ value: 'Nepal', label: 'Nepal', flag: '🇳🇵' },
	{ value: 'Netherlands', label: 'Netherlands', flag: '🇳🇱' },
	{ value: 'New Zealand', label: 'New Zealand', flag: '🇳🇿' },
	{ value: 'Nicaragua', label: 'Nicaragua', flag: '🇳🇮' },
	{ value: 'Niger', label: 'Niger', flag: '🇳🇪' },
	{ value: 'Nigeria', label: 'Nigeria', flag: '🇳🇬' },
	{ value: 'North Macedonia', label: 'North Macedonia', flag: '🇲🇰' },
	{ value: 'Norway', label: 'Norway', flag: '🇳🇴' },
	{ value: 'Oman', label: 'Oman', flag: '🇴🇲' },
	{ value: 'Pakistan', label: 'Pakistan', flag: '🇵🇰' },
	{ value: 'Palau', label: 'Palau', flag: '🇵🇬' },
	{ value: 'Panama', label: 'Panama', flag: '🇵🇦' },
	{ value: 'Papua New Guinea', label: 'Papua New Guinea', flag: '🇵🇬' },
	{ value: 'Paraguay', label: 'Paraguay', flag: '🇵🇾' },
	{ value: 'Peru', label: 'Peru', flag: '🇵🇪' },
	{ value: 'Philippines', label: 'Philippines', flag: '🇵🇭' },
	{ value: 'Poland', label: 'Poland', flag: '🇵🇱' },
	{ value: 'Portugal', label: 'Portugal', flag: '🇵🇹' },
	{ value: 'Qatar', label: 'Qatar', flag: '🇶🇦' },
	{ value: 'Romania', label: 'Romania', flag: '🇷🇴' },
	{ value: 'Russia', label: 'Russia', flag: '🇷🇺' },
	{ value: 'Rwanda', label: 'Rwanda', flag: '🇷🇼' },
	{ value: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis', flag: '🇰🇳' },
	{ value: 'Saint Lucia', label: 'Saint Lucia', flag: '🇱🇨' },
	{ value: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
	{ value: 'Samoa', label: 'Samoa', flag: '🇼🇸' },
	{ value: 'San Marino', label: 'San Marino', flag: '🇸🇲' },
	{ value: 'Sao Tome and Principe', label: 'Sao Tome and Principe', flag: '🇸🇹' },
	{ value: 'Saudi Arabia', label: 'Saudi Arabia', flag: '🇸🇦' },
	{ value: 'Senegal', label: 'Senegal', flag: '🇸🇳' },
	{ value: 'Serbia', label: 'Serbia', flag: '🇷🇸' },
	{ value: 'Seychelles', label: 'Seychelles', flag: '🇸🇨' },
	{ value: 'Sierra Leone', label: 'Sierra Leone', flag: '🇸🇱' },
	{ value: 'Singapore', label: 'Singapore', flag: '🇸🇬' },
	{ value: 'Slovakia', label: 'Slovakia', flag: '🇸🇰' },
	{ value: 'Slovenia', label: 'Slovenia', flag: '🇸🇮' },
	{ value: 'Solomon Islands', label: 'Solomon Islands', flag: '🇸🇧' },
	{ value: 'Somalia', label: 'Somalia', flag: '🇸🇴' },
	{ value: 'South Africa', label: 'South Africa', flag: '🇿🇦' },
	{ value: 'South Sudan', label: 'South Sudan', flag: '🇸🇸' },
	{ value: 'Spain', label: 'Spain', flag: '🇪🇸' },
	{ value: 'Sri Lanka', label: 'Sri Lanka', flag: '🇱🇰' },
	{ value: 'Sudan', label: 'Sudan', flag: '🇸🇩' },
	{ value: 'Suriname', label: 'Suriname', flag: '🇸🇷' },
	{ value: 'Sweden', label: 'Sweden', flag: '🇸🇪' },
	{ value: 'Switzerland', label: 'Switzerland', flag: '🇨🇭' },
	{ value: 'Syria', label: 'Syria', flag: '🇸🇾' },
	{ value: 'Taiwan', label: 'Taiwan', flag: '🇹🇼' },
	{ value: 'Tajikistan', label: 'Tajikistan', flag: '🇹🇯' },
	{ value: 'Tanzania', label: 'Tanzania', flag: '🇹🇿' },
	{ value: 'Thailand', label: 'Thailand', flag: '🇹🇭' },
	{ value: 'Timor-Leste', label: 'Timor-Leste', flag: '🇹🇱' },
	{ value: 'Togo', label: 'Togo', flag: '🇹🇬' },
	{ value: 'Tonga', label: 'Tonga', flag: '🇹🇴' },
	{ value: 'Trinidad and Tobago', label: 'Trinidad and Tobago', flag: '🇹🇹' },
	{ value: 'Tunisia', label: 'Tunisia', flag: '🇹🇳' },
	{ value: 'Turkey', label: 'Turkey', flag: '🇹🇷' },
	{ value: 'Turkmenistan', label: 'Turkmenistan', flag: '🇹🇲' },
	{ value: 'Tuvalu', label: 'Tuvalu', flag: '🇹🇻' },
	{ value: 'Uganda', label: 'Uganda', flag: '🇺🇬' },
	{ value: 'Ukraine', label: 'Ukraine', flag: '🇺🇦' },
	{ value: 'United Arab Emirates', label: 'United Arab Emirates', flag: '🇦🇪' },
	{ value: 'United Kingdom', label: 'United Kingdom', flag: '🇬🇧' },
	{ value: 'United States', label: 'United States', flag: '🇺🇸' },
	{ value: 'Uruguay', label: 'Uruguay', flag: '🇺🇾' },
	{ value: 'Uzbekistan', label: 'Uzbekistan', flag: '🇺🇿' },
	{ value: 'Vanuatu', label: 'Vanuatu', flag: '🇻🇺' },
	{ value: 'Vatican City', label: 'Vatican City', flag: '🇻🇦' },
	{ value: 'Venezuela', label: 'Venezuela', flag: '🇻🇪' },
	{ value: 'Vietnam', label: 'Vietnam', flag: '🇻🇳' },
	{ value: 'Yemen', label: 'Yemen', flag: '🇾🇪' },
	{ value: 'Zambia', label: 'Zambia', flag: '🇿🇲' },
	{ value: 'Zimbabwe', label: 'Zimbabwe', flag: '🇿🇼' }
];

export default Nationalities;