USE `essentialmode`;

ALTER TABLE `users`
	ADD COLUMN `firstname` VARCHAR(15) NULL DEFAULT NULL,
	ADD COLUMN `lastname` VARCHAR(15) NULL DEFAULT NULL,
	ADD COLUMN `dateofbirth` VARCHAR(10) NULL DEFAULT NULL,
	ADD COLUMN `sex` VARCHAR(1) NULL DEFAULT NULL,
	ADD COLUMN `height` VARCHAR(3) NULL DEFAULT NULL
;