INSERT INTO `items` (`name`, `label`) VALUES
('alive_chicken', 'Poulet vivant'),
('slaughtered_chicken', 'Poulet abattu'),
('packaged_chicken', 'Poulet en barquette'),
('fish', 'Poisson'),
('stone', 'Pierre'),
('washed_stone', 'Pierre Lavée'),
('copper', 'Cuivre'),
('iron', 'Fer'),
('gold', 'Or'),
('diamond', 'Diamant'),
('wood', 'Bois'),
('cutted_wood', 'Bois coupé'),
('packaged_plank', 'Paquet de planches'),
('petrol', 'Pétrole'),
('petrol_raffin', 'Pétrole Raffiné'),
('essence', 'Essence'),
('whool', 'Laine'),
('fabric', 'Tissu'),
('clothe', 'Vêtement');