Locales['es'] = {
	--- CCTV Strings ------

	["take_picture"] = "Tomar foto",
	["rot_left_right"] = "Izquierda/Derecha",
	["rot_up_down"] = "Arriba/Abajo",
	["zoom"] = "Zoom +/-",
	["zoom_level"] = "Nivel de Zoom: %s %%",
	["night_vision"] = "Alternar Visión Nocturna",
	["clipboard"] = "Enlace copiado al ~b~Portapapeles",
	["picture_taken"] = "¡Foto tomada!",
	["please_wait"] = "Espere antes de tomar otra ~b~Foto",
	["exit"] = "Salir",

	--- Furniture Strings ------

	["height"] = "Altura",
	["rotate"] = "Rotación",
	["place"] = "Colocar mueble",
	["delete_furni"] = "Borrar",
	["confirm_buy"] = "¿Quieres comprar %s?",
	["price"] = "Precio: $%s",
	["yes"] = "Si",
	["no"] = "No",
	["action"] = "¡ Tu %s ~b~%s~s~ !",
	["bought_furni"] = "¡ Has ~g~comprado~s~ un ~b~%s~s~ !",
	["edited_furni"] = "¡ Has editado ~b~%s~s~ !",
	["cannot_buy"] = "¡~r~No puedes~s~ comprar esto!",
	["cannot_edit"] = "¡Usted ~r~no puede~s~ editar esto!",
	["store_title"] = "Tienda - %s",
	["back"] = "Volver",
	["edit_title"] = "Edición - %s",
	["move_title"] = "Mover",
	["delete_confirm"] = "¡Borrado ~b~%s~s~!",
	["delete_error"] = "No se puede borrar ~b~%s~s~!",
	["owned_furni"] = "Mobiliario propio",
	["menu_stores"] = "Tiendas de muebles",
	["menu_stores_desc"] = "Comprar mueble",
	["menu_reset"] = "Reiniciar",
	["menu_reset_desc"] = "Limpia todos los muebles",
	["menu_edit"] = "Editar",
	["menu_edit_desc"] = "Mover y/o Eliminar muebles",
	["furni_command"] = "muebles",
	["furni_command_desc"] = "Abrir menú de muebles",
	["furni_command_permission"] = "~r~No~s~ puede acceder a este menú.",
	["furni_reset_success"] = "¡Todos los muebles reiniciados!",
	["furni_cannot_afford"] = "¡Usted no puede permitirse el lujo de hacer esto!",
	["furni_reset_error"] = "~r~No puede~s~ ¡Restablecer esta propiedad!",
	["furni_management"] = "Administrar muebles",

	--------- Key Strings ---------------

	["you_granted"] = 'Se le han otorgado llaves a ~b~%s~s~.',
	["already_has"] = "¡Este jugador ya tiene llaves!",
	["do_not_own"] = 'Usted ~r~no~s~ es dueño de esta propiedad.',
	["key_revoked"] = 'Su llave de acceso a ~b~%s~s~. ha sido ~r~revocada~s~',
	["no_keys"] = "¡Este jugador no tiene llaves!",
	["nearby"] = "Jugadores cercanos",
	["gave_key"] = "Entrega de llaves a %s!",
	["key_cannot_give"] = "No puedes darle a este jugador una ~r~Llave",
	["remove_title"] = "Eliminar llaves del jugador",
	["key_revoke_success"] = "Revocación de llaves de ~b~%s~s~.",
	["key_revoke_error"] = "No puede ~b~quitar~s~ las ~r~llave~s~ a esta persona",
	["key_management"] = "Gestión de llaves",
	["key_management_desc"] = "Controlar el acceso a la propiedad.",
	["give_keys"] = "Dar llaves",
	["remove_keys"] = "Quitar llaves",

	--------- Real Estate Strings ---------------

	["office_blip"] = "Oficina de %s",
	["actions"] = "Acciones Inmobiliarias",
	["property_create"] = "Crear propiedad",
	["property_manage"] = "Administrar propiedades",
	["realestate_command"] = "realestatequickmenu",
	["realestate_command_desc"] = "(ESX Property) Abrir acciones rápidas inmobiliarias",
	["enter_office"] = "~b~Entrando~a~la oficina.",
	["enter_office_error"] = "¡Usted ~r~no puede~s~ entrar en la oficina!",
	["exit_office"] = "~b~Saliendo~s~ de la oficina.",
	["exit_office_error"] = "¡Usted ~r~no puede~s~ salir de la oficina!",
	["realestate_textui"] = "Presione ~b~[E]~s~ para acceder ~b~%s",

	------------Command Strings-------------------------------

	["refresh_name"] = "property:refresh",
	["refresh_desc"] = "Actualizar al estado de inicio del servidor",
	["save_name"] = "property:save",
	["save_desc"] = "Forzar guardar propiedades",
	["create_name"] = "property:create",
	["create_desc"] = "Crear una nueva propiedad",
	["admin_name"] = "property:admin",
	["admin_desc"] = "Administrar/ver todas las propiedades",

	---------- Property Actions Menu  -------------------------

	["knocking"] = "Alguien Está ~b~Llamando~s~ A La Puerta.",
	["name_edit"] = "Editar nombre de propiedad",
	["name"] = "Nombre",
	["confirm"] = "Confirmar",
	["name_edit_success"] = "Ha establecido el nombre de la propiedad a ~b~%s~s~.",
	["name_edit_error"] = "No puede establecer el nombre de la propiedad a ~r~%s~s~.",
	["door_locked"] = "Puerta: cerrada",
	["door_unlocked"] = "Puerta: abierta",
	["name_manage"] = "Administrar nombre",
	["name_manage_desc"] = "Establezca el nombre de la propiedad.",
	["sell_title"] = "Vender",
	["sell_desc"] = "Vender esta propiedad por $%s",
	["raid_title"] = "Redada",
	["raid_desc"] = "Forzar la entrada a la propiedad.",
	["cctv_title"] = "CCTV",
	["cctv_desc"] = "Compruebe el circuito cerrado de televisión.",
	["inventory_title"] = "Inventario",
	["inventory_desc"] = "Cambiar la posición del inventario de propiedad.",
	["wardrobe_title"] = "Armario",
	["wardrobe_desc"] = "Cambiar la posición del armario de la propiedad.",
	["furniture_title"] = "Muebles",
	["furniture_desc"] = "Cambiar Posición de Mobiliario de Propiedad.",
	["enter_title"] = "Entrar",
	["knock_title"] = "Tocar la puerta",
	["buy_title"] = "Comprar",
	["buy_desc"] = "Compre esta propiedad por $%s",
	["sellplayer_title"] = "Vender al jugador",
	["sellplayer_desc"] = "Vender esta propiedad por $%s",
	["view_title"] = "Vista previa del interior",
	["exit_title"] = "Salir",
	["property_editing_error"] = "Actualmente está editando la propiedad.",
	["unlock_error"] = "No puede ~b~desbloquear~s~ esta propiedad",
	["lock_error"] = "No puede ~bloquear~a~ esta propiedad",
	["prep_raid"] = "¡~b~Preparando~s~ Redada!",
	["raiding"] = "Asaltando...",
	["cancel_raiding"] = "¡Redada ~r~Cancelada~s~!",
	["cannot_raid"] = "No puedes ~b~Asaltar~s~ esta propiedad.",
	["storage_pos_textui"] = "Presione ~b~[G]~s~ para establecer la posición del inventario",
	["storage_pos_success"] = "Posición del ~b~Inventario~s~ establecida.",
	["storage_pos_error"] = "~r~No se puede~s~ establecer la posición de ~b~inventario~s~.",
	["wardrobe_pos_textui"] = "Presione ~b~[G]~s~ para establecer la posición del Armario",
	["wardrobe_pos_success"] = "Posición del ~b~Armario~s~ establecida.",
	["wardrobe_pos_error"] = "~r~No se puede~s~ establecer la posición de ~b~armario~s~.",
	["please_finish"] = "Finalice la configuración de posición de ~b~%s~s~",
	["cannot_afford"] = "¡Usted no puede comprar esta propiedad!",
	["select_player"] = "Seleccionar jugador",
	["cannot_sell"] = "¡No se puede vender a este jugador!",
	["knock_on_door"] = "Llamando a la puerta...",
	["nobody_home"] = "Parece que nadie está en casa...",

	---------- General Strings ----------------

	["enabled"] = "Activado",
	["disabled"] = "Desactivado",
	["exiting"] = "Saliendo de la propiedad...",
	["entering"] = "Entrando a la propiedad...",
	["shell_disabled"] = "¡Este interior usa shells, que están deshabilitados!",
	["access_textui"] = "Pulsa ~b~[E]~s~ para acceder ~b~%s",
	["raid_notify_error"] = "Necesitas ~b~ %sx %s~s~  para poder asaltar!",
	["raid_notify_success"] = "¡Su propiedad está siendo actualmente ~b~Asaltada!",

	--------------- Garage Strings --------------

	["store_success"] = "Vehículo ~b~¡Almacenado!",
	["store_error"] = "¡No puede almacenar este vehículo!",
	["property_garage"] = "Garaje de propiedad",
	["retriving_notify"] = "Sacando ~b~%s~s~ ...",
	["cannot_access"] = "¡No puede acceder a este garaje!",
	["store_textui"] = "Pulsa ~b~[E]~s~ para almacenar ~b~%s",
	["garage_not_enabled"] = 'Garaje No Habilitado En Esta Propiedad.',
	["cannot_access_property"] = '~r~No puede~s~ Acceder a esta propiedad.',

	----------------- Creation Menu Strings ----------------

	["menu_title"] = "Creación de propiedad",
	["element_title1"] = "Número de calle",
	["element_description1"] = "Establezca el número de calle de la propiedad.",
	["element_title2"] = "Precio",
	["element_description2"] = "Fijar el Precio de la Propiedad.",
	["element_title3"] = "Interior",
	["element_description3"] = "Seleccione un interior para la propiedad",
	["element_title4"] = "Garaje",
	["element_description4"] = "(Opcional) Administrar la configuración del garaje",
	["element_title5"] = "CCTV",
	["element_description5"] = "(Opcional) Administrar la configuración de CCTV",
	["element_title6"] = "Entrada",
	["element_description6"] = "Establezca la ubicación de entrada de la propiedad.",
	["element_create_title"] = "Crear propiedad",
	["element_create_desc_1"] = "¡Complete todas las entradas requeridas!",
	["entrance_set_title"] = "Entrada establecida.",
	["entrance_set_description"] = "Entrada: %s, %s, %s",
	["interior_set_title"] = "Interior seleccionado.",
	["interior_set_description"] = "Selected: %s",
	["ipl_title"] = "Interiores IPL",
	["types_title"] = "Tipos de interiores",
	["ipl_description"] = "Interiores nativos de GTA, Hecho por R*",
	["shell_title"] = "Interiores personalizados",
	["shell_description"] = "Interiores personalizados, hechos por Ti",
	["cctv_settings"] = "Ajustes CCTV",
	["garage_settings"] = "Configuración del garaje",
	["toggle_title"] = "Alternar uso",
	["toggle_description"] = "Estado actual: %s",
	["cctv_set_title"] = "Establecer angulo de CCTV",
	["cctv_set_description"] = "Establece el angulo de las cámaras para tus direcciones de Cámaras",
	["back_description"] = "Volver a la creación de propiedad.",
	["garage_set_title"] = "Establecer posición de garaje",
	["garage_set_description"] = "Establece la posición del garaje de la propiedad.",
	["garage_textui"] = "Presione ~b~[E]~s~ para establecer la posición",
	["cctv_textui_1"] = "Presione ~b~[E]~s~ para establecer el ángulo",
	["cctv_textui_2"] = "Presione ~b~[E]~s~ para establecer la rotación máxima a la derecha",
	["cctv_textui_3"] = "Presione ~b~[E]~s~ para establecer la rotación máxima a la izquierda",
	["create_success"] = "¡Propiedad creada!",
	["missing_data"] = "¡Complete todas las entradas requeridas!",

	-- Saving Translations
	["server_restart"] = "Reinicio del servidor",
	["server_shutdown"] = "Apagado del servidor",
	["manual_save"] = "Guardado manual (solicitado por %s)",
	["resource_stop"] = "Detención de recurso",
	["force_save"] = "Forzar guardado (solicitado por %s)",
	["interval_saving"] = "Intervalo de Guardado"
}
