Locales['it'] = {
  ['shop_robbery'] = 'rapine negozi',
  ['press_to_rob'] = 'premi [E] per ~o~avviare una rapina %s',
  ['robbery_timer'] = 'rapina: ~r~%s secondi rimanenti',
  ['recently_robbed'] = 'questo negozio è stato recentemente rapinato. Attendi  %s secondi prima di poter avviare una nuova rapina',
  ['rob_in_prog'] = '~r~rapina in corso %s',
  ['started_to_rob'] = 'hai iniziato a derubare %s',
  ['alarm_triggered'] = 'l\'allarme è stato attivato',
  ['robbery_complete'] = '~r~la rapina ha avuto successo, hai ~o~rubato $%s',
  ['robbery_complete_at'] = '~r~rapina riuscita %s',
  ['robbery_cancelled'] = 'la rapina è stata annullata!',
  ['robbery_cancelled_at'] = '~r~la rapina a %s è stata annullata!',
  ['min_police'] = 'devono esserci almeno %s poliziotti in città per avviare una rapina.',
  ['robbery_already'] = '~r~una rapina è già in corso.',
  ['no_threat'] = 'non rappresenti una minaccia per il negoziante',
}
