RegisterNetEvent('esx_healthnarmour:set')
AddEventHandler('esx_healthnarmour:set', function(health, armour)
  local playerPed = PlayerPedId()
  SetEntityHealth(playerPed, health)
  SetPedArmour(playerPed, armour)
end)